name: 'Setup Project'
description: 'Install dependencies, and setup project'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
    - name: Increase inotify watch limit
      run: |
        cat /proc/sys/fs/inotify/max_user_watches
        sudo sysctl -w fs.inotify.max_user_watches=524288
        sudo sysctl -p
      shell: bash
