name: Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
      - run: pnpm run build
      - run: pnpm test
      - run: pnpm lint & pnpm build
        working-directory: ./docs/